import Navbar from "@/components/Navbar";
import "./globals.css";
import { Comfortaa, Inter } from "next/font/google";

const comfortaa = Comfortaa({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className='m-2 '>
            <body className={`${comfortaa.className}`}>{children}</body>
        </html>
    );
}
